#!/bin/bash

mkdir /tmp/lecture_slides
mkdir /tmp/lecture_slides/CRSY
mkdir /tmp/lecture_slides/CRSY/BBC_videos
mkdir /tmp/lecture_slides/CRSY/seminars
mkdir /tmp/lecture_slides/DART

# CRSY
rsync --rsh=ssh --archive --delete --verbose --times /Volumes/GoogleDrive/My\ Drive/lecturing_stuff/archive_material/CRS/BBC_videos/*.mp4 /tmp/lecture_slides/CRSY/BBC_videos/
rsync --rsh=ssh --archive --delete --verbose --times /Volumes/GoogleDrive/My\ Drive/lecturing_stuff/CRS/L*.pptx /tmp/lecture_slides/CRSY/
rsync --rsh=ssh --archive --delete --verbose --times /Volumes/GoogleDrive/My\ Drive/lecturing_stuff/CRS/P*.docx /tmp/lecture_slides/CRSY/
rsync --rsh=ssh --archive --delete --verbose --times /Volumes/GoogleDrive/My\ Drive/lecturing_stuff/CRS/seminars/ /tmp/lecture_slides/CRSY/seminars/

# DART
# find ~/Google\ Drive\ File\ Stream/Team\ Drives/ARTS\ Practicals -maxdepth 1 -mindepth 1 -type d -not -name ".*" -print0| xargs -L 1 -0 basename  | while read dir
# do
# 	echo "Directory" $dir
# 	rsync --rsh=ssh --progress --archive --delete --delete-excluded --verbose --times "/Users/ijb/Google Drive File Stream/Team Drives/ARTS Practicals/$dir/" "/Users/ijb/Google Drive File Stream/My Drive/lecturing_stuff/ARTS/Practicals/$dir/"
# done

# rsync --rsh=ssh --archive --delete --verbose --times --delete-excluded --exclude /o* /Volumes/GoogleDrive/My\ Drive/lecturing_stuff/ARTS/*.p* /tmp/lecture_slides/DART/

cp -av /Volumes/GoogleDrive/My\ Drive/lecturing_stuff/ARTS/*.pp* /tmp/lecture_slides/DART/

rsync --rsh=ssh --archive --delete --verbose --times --delete-excluded --exclude "/other stuff" --exclude "Ico*" --exclude "NOTE*" /Volumes/GoogleDrive/My\ Drive/lecturing_stuff/ARTS/Practicals/ /tmp/lecture_slides/DART/Practicals/

rsync --rsh=ssh --archive --delete --verbose --times /tmp/lecture_slides/ ijb500@csresearch1.york.ac.uk://usr/userfs/i/ijb500/w2k/Desktop/

