#!/bin/sh
if /sbin/mount | grep -q "Time Machine"; then
	rsync --rsh=ssh --archive --delete --delete-excluded --verbose --times /Users/ijb/tmp/ ijb@headfoo://local/d0p3/ijb/tmp/tmp_from_mac/
	rsync --rsh=ssh --archive --delete --delete-excluded --verbose --times /Users/ijb/Movies/ ijb@headfoo://local/d0p3/ijb/tmp/Movies_from_mac/
	rsync --rsh=ssh --archive --delete --delete-excluded --verbose --times /Users/ijb/Pictures/ ijb@headfoo://local/d0p3/ijb/tmp/Pictures_from_mac/
fi
